production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 25
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
