version: '3.1'

# note: APP_DIR, DOCKER_PATH, and DEV_PATH are set as a convenience by `nbx dev`

services:
  # the postgres database
  db:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    env_file:
      - '.env'
  
  # the rails web service
  web:
    build:
      context: ${APP_DIR}
      dockerfile: ${DEV_PATH}/Dockerfile
      args:
        DEV_PATH: ${DEV_PATH}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ${APP_DIR}:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - '.env'

volumes:
  db_data:
